version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  app: ## nome do serviço
    build: . ## localização do dockerfile
    container_name: container-api-coleta-seletiva
    command: npm run dev ## comando a executar
    ports:
      - "${PORT}:${PORT}" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    volumes:
      - .:/usr/app ## monitoro a pasta atual . e envio as alterações para /usr/app
    networks:
      - backend
networks:
  backend:
    name: network-api-coleta-seletiva
    driver: bridge
